const express = require('express')
const router = express.Router()
const { createProduct, getAllProducts, getProduct, updateProduct, deleteProduct, getLowStockProducts, getFlashSales, getFilterOptions } = require('../controller/product.controller')
const { upload } = require('../config/cloudinary')
const { authMiddleware, adminOrSellerMiddleware } = require('../middleware/auth.middleware')
router.post('/', authMiddleware, adminOrSellerMiddleware, upload.array('media', 10), createProduct)
router.get('/filters', getFilterOptions)
router.get('/', getAllProducts)
router.get('/low-stock', authMiddleware, adminOrSellerMiddleware, getLowStockProducts)
router.get('/flash-sales', getFlashSales)
router.get('/:id', getProduct)
router.put('/:id', authMiddleware, adminOrSellerMiddleware, upload.array('media', 10), updateProduct)
router.delete('/:id', authMiddleware, adminOrSellerMiddleware, deleteProduct)
module.exports = router